# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WKyqC3knFlx57nE9ZyAb3c1zcZxhFyvD
"""

dictionary = {"mon": 19, "jai": 99, "mahi" :100}
name = input("enter the students name: ")

if name in dictionary:
  marks = dictionary[name]
  print(f"{name}'s  marks: student{[marks]}")
else:
  print(f"Student not found")

a = [1,2,3,4,5,6,7,8,9,10]
b = a [:5]
print(b)
b.reverse()
print(b)

